### ISSUE TITLE
Entrevista de la web 1.0 , 2.0 , 3.0

### ISSUE THREAD

**Issue by Jaczibeth** [SistemasTecTlaxiaco/actividad-8-entrevista-equipo-7#1]
Equipo 7
1BS
[ENTREVISTA SOBRE LAS WEBS-1.0.docx](https://github.com/SistemasTecTlaxiaco/actividad-8-entrevista-equipo-7/files/9897708/ENTREVISTA.SOBRE.LAS.WEBS-1.0.docx)

**Comment by 11042002** [comment]
Tu calificación es de: 18%

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
